"""source chunks and version storage key

Revision ID: 219d64ce1832
Revises: 27b07774353b
Create Date: 2026-10-08 16:58:11.230381

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "219d64ce1832"
down_revision: str | None = "27b07774353b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("locator_type", sa.String(length=20), nullable=False),
        sa.Column("locator_value", sa.String(length=50), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["version_id"], ["material_versions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_chunks_version_id"), "source_chunks", ["version_id"], unique=False
    )
    op.add_column(
        "material_versions", sa.Column("storage_key", sa.String(length=300), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("material_versions", "storage_key")
    op.drop_index(op.f("ix_source_chunks_version_id"), table_name="source_chunks")
    op.drop_table("source_chunks")
    # ### end Alembic commands ###
