"""version checksum for duplicate detection

Revision ID: 35042b675637
Revises: 219d64ce1832
Create Date: 2026-10-10 08:45:10.744790

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35042b675637"
down_revision: str | None = "219d64ce1832"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("material_versions", sa.Column("checksum", sa.String(length=64), nullable=True))
    op.create_index(
        op.f("ix_material_versions_checksum"), "material_versions", ["checksum"], unique=False
    )
    op.drop_constraint(op.f("uq_source_chunks_version_seq"), "source_chunks", type_="unique")
    op.drop_column("source_chunks", "bbox_x1")
    op.drop_column("source_chunks", "paragraph")
    op.drop_column("source_chunks", "bbox_y0")
    op.drop_column("source_chunks", "confidence")
    op.drop_column("source_chunks", "bbox_y1")
    op.drop_column("source_chunks", "bbox_x0")
    op.drop_column("source_chunks", "page")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "source_chunks", sa.Column("page", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "source_chunks",
        sa.Column("bbox_x0", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "source_chunks",
        sa.Column("bbox_y1", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "source_chunks",
        sa.Column(
            "confidence", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "source_chunks",
        sa.Column("bbox_y0", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "source_chunks", sa.Column("paragraph", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "source_chunks",
        sa.Column("bbox_x1", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.create_unique_constraint(
        op.f("uq_source_chunks_version_seq"),
        "source_chunks",
        ["version_id", "seq"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_material_versions_checksum"), table_name="material_versions")
    op.drop_column("material_versions", "checksum")
    # ### end Alembic commands ###
