"""task source material link

Revision ID: 6d68b7c18adb
Revises: 35042b675637
Create Date: 2026-10-10 14:09:37.838358

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d68b7c18adb"
down_revision: str | None = "35042b675637"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("source_material_id", sa.Integer(), nullable=True))
    op.create_index(
        op.f("ix_tasks_source_material_id"), "tasks", ["source_material_id"], unique=False
    )
    op.create_foreign_key(
        None, "tasks", "materials", ["source_material_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_tasks_source_material_id"), table_name="tasks")
    op.drop_column("tasks", "source_material_id")
    # ### end Alembic commands ###
