"""processing jobs

Revision ID: 7aa842f421d7
Revises: 6d68b7c18adb
Create Date: 2026-10-10 15:14:25.630975

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aa842f421d7"
down_revision: str | None = "6d68b7c18adb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("scope", sa.String(length=500), nullable=True),
        sa.Column("error_reason", sa.String(length=500), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["material_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_processing_jobs_material_id"), "processing_jobs", ["material_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_version_id"), "processing_jobs", ["version_id"], unique=False
    )
    op.create_index(
        op.f("ix_processing_jobs_workspace_id"), "processing_jobs", ["workspace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, "tasks", type_="foreignkey")
    op.drop_index(op.f("ix_processing_jobs_workspace_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_version_id"), table_name="processing_jobs")
    op.drop_index(op.f("ix_processing_jobs_material_id"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    # ### end Alembic commands ###
