"""chunk coordinates and idempotent unique

Revision ID: 9e2e4f0eb119
Revises: 219d64ce1832
Create Date: 2026-10-09 10:55:50.409834

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e2e4f0eb119"
down_revision: str | None = "219d64ce1832"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("source_chunks", sa.Column("page", sa.Integer(), nullable=True))
    op.add_column("source_chunks", sa.Column("paragraph", sa.Integer(), nullable=True))
    op.add_column("source_chunks", sa.Column("bbox_x0", sa.Float(), nullable=True))
    op.add_column("source_chunks", sa.Column("bbox_y0", sa.Float(), nullable=True))
    op.add_column("source_chunks", sa.Column("bbox_x1", sa.Float(), nullable=True))
    op.add_column("source_chunks", sa.Column("bbox_y1", sa.Float(), nullable=True))
    op.add_column("source_chunks", sa.Column("confidence", sa.Float(), nullable=True))
    op.create_unique_constraint(
        "uq_source_chunks_version_seq", "source_chunks", ["version_id", "seq"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_source_chunks_version_seq", "source_chunks", type_="unique")
    op.drop_column("source_chunks", "confidence")
    op.drop_column("source_chunks", "bbox_y1")
    op.drop_column("source_chunks", "bbox_x1")
    op.drop_column("source_chunks", "bbox_y0")
    op.drop_column("source_chunks", "bbox_x0")
    op.drop_column("source_chunks", "paragraph")
    op.drop_column("source_chunks", "page")
    # ### end Alembic commands ###
